# Generated by Django 4.2.1 on 2023-06-01 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url_message', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120, null=True)),
                ('tg_user_id', models.IntegerField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('session', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Сообщение из чата',
                'verbose_name_plural': 'Сообщения из чатов',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=75, verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('api_id', models.IntegerField()),
                ('api_hash', models.CharField(max_length=50)),
                ('session_name', models.CharField(max_length=40, unique=True, verbose_name='Сессия')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('phone_code_hash', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=10, verbose_name='Пароль')),
                ('recipient', models.CharField(max_length=30, verbose_name='Получатель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excluded_words_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tab_excluded', to='tgparser.table', verbose_name='Фразы исключения')),
                ('keywords_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tab_keywords', to='tgparser.table', verbose_name='Ключевые фразы')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конфигурация бота',
                'verbose_name_plural': 'Конфигурации ботов',
            },
        ),
        migrations.CreateModel(
            name='BlockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User ID')),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заблокированный пользователь',
                'verbose_name_plural': 'Заблокированные пользователи',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100, verbose_name='Фраза')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_phrases', to='tgparser.table')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
                'unique_together': {('phrase', 'table')},
            },
        ),
    ]
