# Generated by Django 4.2.1 on 2023-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedusers',
            name='tg_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mersinchatmessages',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mersinchatmessages',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mersinchatmessages',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mersinchatmessages',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
