# Generated by Django 4.2.1 on 2023-05-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_blockedusers_tg_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedusers',
            name='tg_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
