# Generated by Django 4.2.1 on 2023-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_blockedusers_tg_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedusers',
            options={'verbose_name': 'По умолчанию: Заблокированные пользователи', 'verbose_name_plural': 'По умолчанию: Заблокированные пользователи'},
        ),
        migrations.AlterModelOptions(
            name='excludedwords',
            options={'verbose_name': 'По умолчанию: Фразы исключения', 'verbose_name_plural': 'По умолчанию: Фразы исключения'},
        ),
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'По умолчанию: Ключевые фразы', 'verbose_name_plural': 'По умолчанию: Ключевые фразы'},
        ),
        migrations.AlterModelOptions(
            name='mersinchatmessages',
            options={'verbose_name': 'Сообщения чата - Мерсин', 'verbose_name_plural': 'Сообщения чата - Мерсин'},
        ),
        migrations.AlterField(
            model_name='blockedusers',
            name='tg_user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='excludedwords',
            name='phrase',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='phrase',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
