# Generated by Django 4.2.1 on 2023-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_blockedusers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('session_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=30)),
                ('api_id', models.IntegerField(max_length=20)),
                ('api_hash', models.CharField(max_length=50)),
                ('messages_table', models.CharField(max_length=100)),
                ('keywords_table', models.CharField(default='tables_keywords', max_length=100)),
                ('excluded_words_table', models.CharField(default='tables_excludedwords', max_length=100)),
                ('blocked_users_table', models.CharField(default='tables_blockedusers', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Боты',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
