# Generated by Django 4.2.1 on 2023-05-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_bots_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='session_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='mersinchatmessages',
            name='phone',
            field=models.CharField(help_text='ссылка https://google.ru', max_length=100, null=True),
        ),
    ]
