# Generated by Django 4.2.1 on 2023-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_bots_session_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='phone',
            field=models.CharField(help_text='ссылка https://google.ru', max_length=30),
        ),
        migrations.AlterField(
            model_name='mersinchatmessages',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
