# Generated by Django 4.2.1 on 2023-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_alter_bots_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='phone',
            field=models.CharField(help_text="Скрипт <a href='{{% url 'start' task.id %}}'>Ссылка</a>", max_length=30),
        ),
    ]
