# Generated by Django 4.2.1 on 2023-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_alter_bots_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='phone',
            field=models.CharField(help_text='<form method="get" action="/tables/script/">\n  <label for="phone">Введите телефон:</label>\n  <input type="text" id="phone" name="phone">\n  <button type="submit">Отправить</button>\n</form>', max_length=30),
        ),
    ]
