# Generated by Django 4.2.1 on 2023-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_alter_bots_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='phone',
            field=models.CharField(help_text="Скрипт <a href='/tables/script/' target='_blank'>Ссылка</a>", max_length=30),
        ),
    ]
