# Generated by Django 4.2.1 on 2023-05-09 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_alter_bots_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bots',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bots',
            name='phone',
            field=models.CharField(help_text="Отправить код <a href='/tables/script/' target='_blank'>Клик</a>", max_length=30),
        ),
    ]
