# Generated by Django 4.2.1 on 2023-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_bots_code_bots_password_alter_bots_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='phone',
            field=models.CharField(help_text='\n<input type="text" name="api_hash" value="0c5adec1271f738ef27ca9abf4553870" class="vTextField" maxlength="50" required="" id="id_api_hash">\n<a href="#" id="link">Клик</a>\n\n<script>\n    document.getElementById(\'link\').addEventListener(\'click\', function(e) {\n        e.preventDefault();\n        \n        var apiHash = document.getElementById(\'id_api_hash\').value;\n        var url = \'/tables/script/?api_hash=\' + encodeURIComponent(apiHash);\n        \n        window.open(url, \'_blank\');\n    });\n</script>\n', max_length=30),
        ),
    ]
