# Generated by Django 4.2.1 on 2023-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_alter_bots_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='code',
            field=models.IntegerField(help_text="Отправить код <a href='/tables/script/' target='_blank'>Клик</a>"),
        ),
    ]
