# Generated by Django 4.2.1 on 2023-05-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_alter_bots_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='code',
        ),
    ]
