# Generated by Django 4.2.1 on 2023-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_remove_bots_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='phone_code_hash',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
