# Generated by Django 4.2.1 on 2023-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_bots_phone_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='phone_code_hash',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
