# Generated by Django 4.2.1 on 2023-05-10 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_alter_bots_phone_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='phone_code_hash',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
