# Generated by Django 4.2.1 on 2023-05-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_alter_bots_phone_code_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('tables_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
