# Generated by Django 4.2.1 on 2023-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_alter_phrases_tables_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phrases',
            new_name='Phrase',
        ),
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
        migrations.AlterField(
            model_name='bots',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
