# Generated by Django 4.2.1 on 2023-05-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0026_rename_phrases_phrase_rename_tables_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='tables_id',
            new_name='table_id',
        ),
    ]
