# Generated by Django 4.2.1 on 2023-05-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0027_rename_tables_id_phrase_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('api_id', models.IntegerField()),
                ('api_hash', models.CharField(max_length=50)),
                ('session_name', models.CharField(max_length=40, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('phone_code_hash', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('recipient', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Конфигурация бота',
                'verbose_name_plural': 'Конфигурации ботов',
            },
        ),
        migrations.RenameModel(
            old_name='MersinChatMessages',
            new_name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Bots',
        ),
        migrations.AlterModelOptions(
            name='blockedusers',
            options={'verbose_name': 'Заблокированный пользователь', 'verbose_name_plural': 'Заблокированные пользователи'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Сообщение из чата', 'verbose_name_plural': 'Сообщения из чатов'},
        ),
        migrations.AlterModelOptions(
            name='phrase',
            options={'verbose_name': 'Фраза', 'verbose_name_plural': 'Фразы'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблицы'},
        ),
        migrations.AlterField(
            model_name='blockedusers',
            name='tg_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blockedusers',
            name='tg_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='excluded_words_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables2', to='tables.table'),
        ),
        migrations.AddField(
            model_name='bot',
            name='keywords_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables1', to='tables.table'),
        ),
    ]
