# Generated by Django 4.2.1 on 2023-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0028_bot_rename_mersinchatmessages_chatmessage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='table_id',
            new_name='table',
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
