# Generated by Django 4.2.1 on 2023-05-10 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0029_rename_table_id_phrase_table_alter_phrase_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
