# Generated by Django 4.2.1 on 2023-05-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0030_chatmessage_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcludedWords',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
    ]
