# Generated by Django 4.2.1 on 2023-05-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0032_rename_is_active_bot_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='session_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Сессия'),
        ),
    ]
