# Generated by Django 4.2.1 on 2023-05-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0033_alter_bot_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='excluded_words_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables2', to='tables.table', verbose_name='Фразы исключения'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='keywords_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables1', to='tables.table', verbose_name='Ключевые фразы'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='recipient',
            field=models.CharField(max_length=30, verbose_name='Получатель'),
        ),
    ]
