# Generated by Django 4.2.1 on 2023-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0034_alter_bot_excluded_words_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='password',
            field=models.CharField(max_length=10, verbose_name='Пароль'),
        ),
    ]
