# Generated by Django 4.2.1 on 2023-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_alter_bot_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='session_name',
            field=models.CharField(help_text='Вспомогательный текст', max_length=40, unique=True, verbose_name='Сессия'),
        ),
    ]
