# Generated by Django 4.2.1 on 2023-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0037_alter_bot_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
