# Generated by Django 4.2.1 on 2023-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0038_table_description_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, max_length=75, verbose_name='Описание'),
        ),
    ]
