# Generated by Django 4.2.1 on 2023-05-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0039_alter_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to='tables.table'),
        ),
    ]
