# Generated by Django 4.2.1 on 2023-05-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0040_alter_phrase_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='excluded_words_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_excluded', to='tables.table', verbose_name='Фразы исключения'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='keywords_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_keywords', to='tables.table', verbose_name='Ключевые фразы'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_phrases', to='tables.table'),
        ),
    ]
