# Generated by Django 4.2.1 on 2023-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0041_alter_bot_excluded_words_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=100, unique=True, verbose_name='Фраза'),
        ),
    ]
