# Generated by Django 4.2.1 on 2023-05-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0042_alter_phrase_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='excluded_words_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tab_excluded', to='tables.table', verbose_name='Фразы исключения'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='keywords_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tab_keywords', to='tables.table', verbose_name='Ключевые фразы'),
        ),
    ]
