# Generated by Django 4.2.1 on 2023-05-31 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0043_alter_bot_excluded_words_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockedusers',
            name='tg_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User ID'),
        ),
    ]
