# Generated by Django 4.2.1 on 2023-05-31 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0045_bot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedusers',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=100, verbose_name='Фраза'),
        ),
    ]
