# Generated by Django 4.2.1 on 2023-06-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0046_blockedusers_owner_alter_phrase_phrase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phrase',
            unique_together={('phrase', 'table')},
        ),
    ]
